---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: crossplane-eks-role
  namespace: crossplane-system
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    description: "IAM Role for Crossplane to manage EKS clusters"
    tags:
      - key: "crossplane"
        value: "eks-role"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: crossplane-eks-role-secret

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: crossplane-eks-policy
  namespace: crossplane-system
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "eks:*",
              "ec2:*",
              "iam:PassRole",
              "elasticloadbalancing:*",
              "autoscaling:*",
              "cloudwatch:*"
            ],
            "Resource": "*"
          }
        ]
      }
    description: "IAM Policy for Crossplane to manage EKS clusters"
    tags:
      - key: "crossplane"
        value: "eks-policy"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: crossplane-eks-policy-secret

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: crossplane-eks-role-attachment
  namespace: crossplane-system
spec:
  forProvider:
    policyArn: "arn:aws:iam::{{ aws:AccountId }}:policy/crossplane-eks-policy"
    roleName: "crossplane-eks-role"